### PR TITLE
Your name still sucks. You should change it.

### LINKED ISSUE #3: Your name for this tool sucks
There is already a widely used tool passwd on each linux system. Even though you use passctl as a commandline utility, the name of the project poorly reflects the use.

This application only works in combination with Team Password Manager.

### PR DESCRIPTION
**Pull request by funzoneq**
Fixes #3

### CODE REVIEW

**Comment by oshu** [comment]
Where is the button for "Worst Project Name Ever" ???

**Comment by spoelwijk** [comment]
whoops

**Comment by RolphH** [comment]
1040newjob

**Comment by oshu** [comment]
annoying-orange-games

**Comment by nrocco** [comment]
Thank you for your contribution!

**Pull request merged**
